#是否开启记录日志功能，开启后每次查询都会发送给REDIS_HOST所在的redis，用于生成web管理界面 统计慢查询等
#开启后会降低30%左右的性能
[common]
record_query = true

#记录客户端sql查询的redis机器
redis_host = "127.0.0.1:6379"

#redis auth
redis_auth = ""

#redis key
redis_slow ="sqlslow"
redis_big="sqlbig"
#用于上报连接数的redis的key
mysql_conn_redis_key="proxy_connection"

#swoole server通用配置信息
worker_num=5
#task 用于上报查询用
task_worker_num=1
#swoole server的 日志
swoole_log="/tmp/sqlproxy.log"

#监听端口
port = 9536
#是否守护进程方式运行
daemon=false

#子node配置文件
#include_path = "/src/mysql-proxy/conf.d/"

#慢日志阈值，超过这个数才记录 单位毫秒 不配置默认100ms
slow_limit = 100

#大数据块阈值，超过这个数才记录 单位字节 不配置默认200kb
big_limit = 204800


#mysql数据源配置

#'node1'名字可以随意改 每个node代表一组主从配置
[node1]
        #主库实例配置
        master_host = "127.0.0.1:3306"

        #主库和从库用户名密码必须一致
        username = "root"
        password= "root"

        #从库实例配置
        slave_host = ["127.0.0.1:3306;weight=1","127.0.0.1:3306;weight=2"]

        #所有允许的数据库名,后面可以可选的配置每个db的charset和最大连接数，如果不配置走默认的
        db = ["name=db1;charset=gbk","name=db2;max_conn=100","name=mysql"] 

        #每个实例每个db默认的最大连接数
        default_max_conn = 20
        #每个db默认的字符集
        default_charset = "utf8"
        #限制客户端ip 不配置就不限制
        client_ip=["192.168.1.%","127.0.0.1"]

#多组node间 dbname不能相同，如果分库后请在每个db后面加后缀，或者启动多个proxy实例，以后支持分库分表后就可以解决了
[node2]
        master_host = "127.0.0.1:3306"
        username = "root"
        #使用genpwd程序生成的加密的密码,配置`encrypt_password`后将忽略password配置
        encrypt_password= "d29zaGlndW8zNQ=="
        slave_host = ["127.0.0.1:3306;weight=1","127.0.0.1:3306;weight=2"]
        #realname是传给mysql server的数据库名,name是客户端连接的名,可以只配置name此时realname等于name
        db = ["name=dummy_mysql;realname=mysql"] 
        default_max_conn = 20
        default_charset = "utf8"
